version: '3.4'

services:
  test-fuse:
    image: ${DOCKER_REGISTRY-}testfuse
    depends_on: 
    - sql-server
    build:
      context: .
      dockerfile: Dockerfile

  sql-server:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: 123456qQ!
      ACCEPT_EULA: "Y"
